// Generated by CoffeeScript 2.7.0
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    console.log('contacts.coffee loaded ✅');
    return document.querySelectorAll('.preview-btn').forEach(function(btn) {
      return btn.addEventListener('click', function() {
        var contactId, parent, select, templateId, url;
        contactId = btn.dataset.contactId;
        parent = btn.closest('.contact-card');
        select = parent.querySelector('.template-select');
        templateId = select.value;
        if (!templateId) {
          alert('Please pick a template');
          return;
        }
        url = `/contacts/${contactId}/preview_template?template_id=${templateId}`;
        return fetch(url).then(function(r) {
          if (!r.ok) {
            throw new Error("Preview failed");
          }
          return r.json();
        }).then(function(json) {
          var preview;
          preview = document.getElementById(`preview-${contactId}`);
          return preview.innerHTML = `<strong>Subject:</strong> ${json.subject}<br/><div style='white-space:pre-wrap;margin-top:8px;'>${json.body}</div>`;
        }).catch(function(err) {
          return alert('Could not load preview');
        });
      });
    });
  });

}).call(this);
